### ISSUE TITLE
Training ae_adv

### ISSUE THREAD

**Issue by yashkotadia** [uvavision/Balanced-Datasets-Are-Not-Enough#2]
Hi,

I am trying to train the U-net Autoencoder approach for adversarial debiasing however I have run into an error where it is trying to load the linear layers of some model.
Can you guide me as to what model weights are expected to be loaded?

Here is the command and error for your reference.

yash@yash-Inspiron-7560:~/Documents/Balanced-Datasets-Are-Not-Enough/object_multilabel/adv$ python ae_adv_train.py --save_dir 6 --log_dir 6 --layer generated_image --adv_lambda 5.0 --batch_size 8 --beta 0.1 --batch_balanced --num_epochs 80 --learning_rate 0.00001 --autoencoder_finetune --adv_on --resume --finetune
CocoObjectGender dataloader
loading train annotations..........
22826
man size : 16225 and woman size: 6601
CocoObjectGender dataloader
loading val annotations..........
5367
man size : 3813 and woman size: 1554
CocoObjectGender dataloader
loading val annotations..........
5367
man size : 1500 and woman size: 1500
Build a ObjectMultiLabelAdv Model[generated_image]
Load weights from Resnet18/50 done
Build a GenderClassification Model
Load weights from Resnet18 done
Traceback (most recent call last):
  File "ae_adv_train.py", line 492, in <module>
    main()
  File "ae_adv_train.py", line 172, in main
    args.adv_lambda).cuda()
  File "/home/yash/Documents/Balanced-Datasets-Are-Not-Enough/object_multilabel/adv/ae_adv_model.py", line 152, in __init__
    gender_clssifier_checkpoint = torch.load(pretrained_gender_classifier_path)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 365, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './model_best_object_balanced.pth.tar'

**Comment by tianlu-wang** [comment]
you need to pretrain a gender classifier defined in ae_adv_model.py (resnet18 as a backbone). I also suggest using gender-balanced data for training.

**Comment by yashkotadia** [comment]
That means I should be running object_multilabel/attacker.py right?

**Comment by tianlu-wang** [comment]
The attacker is a simple MLP model which might also work, but I would suggest using a deeper model (resnet18) since the input is an image.

**Comment by yashkotadia** [comment]
Would I still be able to achieve the results stated in the paper if I train the resnet18 gender classifier while training the adversarial autoencoder model?

**Comment by IMoonKeyBoy** [comment]
@tianlu-wang Do you mean that we need to define a training process to complete the training in ae_adv_model.py (resnet18 as a backbone)? Could you please share this code?
