### ISSUE TITLE
Possible bug in natural_leakage.py

### ISSUE THREAD

**Issue by yashkotadia** [uvavision/Balanced-Datasets-Are-Not-Enough#4]
The probabilities for randomly flipping in the file natural_leakage.py are as shown below

`for p in [0.0195, 0.020, 0.0205, 0.021, 0.022, 0.023, 0.024, 0.026, 0.027, 0.028, 0.03, 0.032, 0.034, 0.036, 0.038, 0.042, 0.044, 0.048, 0.052, 0.056, 0.06, 0.065]`

Note that this line of code is directly from natural_leakage.py

My concern is that shouldn't the list be [0.195, 0.20, 0.205, 0.21, 0.22, 0.23, 0.24, 0.26, 0.27, 0.28, 0.3, 0.32, 0.34, 0.36, 0.38, 0.42, 0.44, 0.48, 0.52, 0.56, 0.6, 0.65] considering these values to be F1 scores.

**Comment by tianlu-wang** [comment]
These values are not F1 score. p is the probability that we use to randomize the ground truth labels.
